name: sel
on:
  push:
    branches: [ "main" ]
jobs:
  dlive:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: sel
        run: |
             pip3 install selenium
             sudo apt install -y firefox
             dir
      - name: Upload file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.Name }}
          path: ${{ env.File }}
          compression-level: 9
