name: sel
on:
  workflow_dispatch:
jobs:
  dlive:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: sel
        run: |
             pip3 install selenium
             sudo apt install -y firefox unzip
             tar -xvzf geckodriver-v0.36.0-linux64.tar.gz
             chmod 777 geckodriver
             unzip ip6t33by.ShitassNigga.zip -d xd
             python3 k.py
      - name: Upload file
        uses: actions/upload-artifact@v4
        with:
          name: d4.png
          path: /home/runner/work/zace32wdawvgrwsaqq1/zace32wdawvgrwsaqq1/d4.png
          compression-level: 9
