name: sel
on:
  push:
    branches: [ "main" ]
jobs:
  dlive:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: sel
        run: |
             pip3 install selenium
             sudo apt update && sudo apt install -y firefox unzip tree
             dir
             pwd
             tar -xvzf geckodriver-v0.36.0-linux64.tar.gz
             ls
             chmod 777 geckodriver
             ls -tgh
             unzip ip6t33by.ShitassNigga.zip -d xd
             dir
             python3 k.py
      - name: Upload file
        uses: actions/upload-artifact@v4
        with:
          name: d4.png
          path: /home/runner/work/zace32wdawvgrwsaqq1/zace32wdawvgrwsaqq1
          compression-level: 9
